# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BusinessMessages.V1.Model.BusinessMessagesRichCard do
  @moduledoc """
  A standalone rich card or a carousel of rich cards sent from the agent to the user.

  ## Attributes

  *   `carouselCard` (*type:* `GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCarouselCard.t`, *default:* `nil`) - Carousel of cards.
  *   `standaloneCard` (*type:* `GoogleApi.BusinessMessages.V1.Model.BusinessMessagesStandaloneCard.t`, *default:* `nil`) - Standalone card.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :carouselCard =>
            GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCarouselCard.t() | nil,
          :standaloneCard =>
            GoogleApi.BusinessMessages.V1.Model.BusinessMessagesStandaloneCard.t() | nil
        }

  field(:carouselCard, as: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCarouselCard)
  field(:standaloneCard, as: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesStandaloneCard)
end

defimpl Poison.Decoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesRichCard do
  def decode(value, options) do
    GoogleApi.BusinessMessages.V1.Model.BusinessMessagesRichCard.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesRichCard do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
