# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestedReply do
  @moduledoc """
  When tapped, sends the text reply back to the agent.

  ## Attributes

  *   `postbackData` (*type:* `String.t`, *default:* `nil`) - The string that the agent receives when a user taps the suggested reply. Maximum 2,048 characters.
  *   `text` (*type:* `String.t`, *default:* `nil`) - Text that is shown in the suggested reply and sent to the agent when the user taps it. Maximum 25 characters.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :postbackData => String.t() | nil,
          :text => String.t() | nil
        }

  field(:postbackData)
  field(:text)
end

defimpl Poison.Decoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestedReply do
  def decode(value, options) do
    GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestedReply.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestedReply do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
