# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BusinessMessages.V1.Model.BusinessMessagesReceipt do
  @moduledoc """
  A receipt of the message.

  ## Attributes

  *   `name` (*type:* `String.t`, *default:* `nil`) - The name of the receipt, as set by Business Messages. Resolves to "conversations/{conversationId}/messages/{messageId}/receipt", where {conversationId} is the unique ID for the conversation and {messageId} is the unique ID for the message.
  *   `receiptType` (*type:* `String.t`, *default:* `nil`) - A receipt type.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :receiptType => String.t() | nil
        }

  field(:name)
  field(:receiptType)
end

defimpl Poison.Decoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesReceipt do
  def decode(value, options) do
    GoogleApi.BusinessMessages.V1.Model.BusinessMessagesReceipt.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesReceipt do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
