# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BusinessMessages.V1.Model.BusinessMessagesImage do
  @moduledoc """
  An image.

  ## Attributes

  *   `contentInfo` (*type:* `GoogleApi.BusinessMessages.V1.Model.BusinessMessagesContentInfo.t`, *default:* `nil`) - Information about an image, including the URL of the image and the URL of the image's thumbnail.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :contentInfo =>
            GoogleApi.BusinessMessages.V1.Model.BusinessMessagesContentInfo.t() | nil
        }

  field(:contentInfo, as: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesContentInfo)
end

defimpl Poison.Decoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesImage do
  def decode(value, options) do
    GoogleApi.BusinessMessages.V1.Model.BusinessMessagesImage.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesImage do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
