# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCardContent do
  @moduledoc """
  Card content.

  ## Attributes

  *   `description` (*type:* `String.t`, *default:* `nil`) - Optional. Description of the card. Maximum 2,000 characters.
  *   `media` (*type:* `GoogleApi.BusinessMessages.V1.Model.BusinessMessagesMedia.t`, *default:* `nil`) - Optional. Media to include in the card.
  *   `suggestions` (*type:* `list(GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestion.t)`, *default:* `nil`) - Optional. List of suggestions to include in the card. Maximum 4 suggestions.
  *   `title` (*type:* `String.t`, *default:* `nil`) - Optional. Title of the card. Maximum 200 characters.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :description => String.t() | nil,
          :media => GoogleApi.BusinessMessages.V1.Model.BusinessMessagesMedia.t() | nil,
          :suggestions =>
            list(GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestion.t()) | nil,
          :title => String.t() | nil
        }

  field(:description)
  field(:media, as: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesMedia)

  field(:suggestions,
    as: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesSuggestion,
    type: :list
  )

  field(:title)
end

defimpl Poison.Decoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCardContent do
  def decode(value, options) do
    GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCardContent.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BusinessMessages.V1.Model.BusinessMessagesCardContent do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
